### ISSUE TITLE
Disable JIRA links

### ISSUE THREAD

**Issue by castalos** [Teaminator/Standup-and-Prosper-FAQ#4]
Is there a way to disable to the JIRA links?  For security reasons, I can't use the integration tool to grant access to JIRA, so the links that Standup & Prosper automatically inserts are confusing - would rather they just don't exist.  Is there a way to disable them?

**Comment by wparad** [comment]
Hey @castalos!

There hopefully isn't a security concern, as Standup & Prosper doesn't require an integration or access to JIRA.

All you would need to do is paste your relevant URL in this field. Standup & Prosper doesn't need special access, your JIRA server doesn't need to be public, this even works if it locked down behind a VPN or firewall.

If there is a security concern, could you please let us know what that is, because we have gone through significant security reviews with some of our customers regarding the features of Standup & Prosper and this has not come up before.

I'm going to recommend due to the sensitive nature and relevance that you reach out to [security @ teaminator.io](mailto:security@teaminator.io) and we can definitely take a look at what would need to be improved for you team.

- Warren

**Comment by castalos** [comment]
Ok, so I guess I'm missing something.  I thought when I was setting up Standup & Prosper that there was something that was asking me to provide credentials to login to JIRA.  (Of course, I can't find that now)

In the configuration for my Standup & Prosper, under advanced tab, there is a section for Automatically insert issue tickets urls when issue tickets are mentioned.  But it's grey'd out.   Do I have to have the paid version to change the URL to what my JIRA URL is?

**Comment by wparad** [comment]
> Ok, so I guess I'm missing something. I thought when I was setting up Standup & Prosper that there was something that was asking me to provide credentials to login to JIRA. (Of course, I can't find that now)

Hopefully not, it really is just a clever regex, a direct url from your standup in slack to your JIRA. There isn't an bot involvement there. If you do find a problem though, we would love to know.

Yes, dynamic issue links for JIRA are part of the paid version of Standup & Prosper. If there's a concern there, we are definitely able to work with your IT department to figure out how to get access for your team, so that property can be updated.

If there is anything we can do on that matter, feel free to reach out to [standup-support @ teaminator.io](mailto:standup-support@teaminator.io).

**Comment by castalos** [comment]
I'm unlikely to be able to get the paid version of Standup & Prosper approved by my organization.   Is there a way to just get the checkbox under the key matching to be unchecked so no text matching occurs? (No links would be better than wrong links) 
![image](https://user-images.githubusercontent.com/121258103/209231559-c708e847-73bb-446b-a7b6-2b557f61b9cd.png)

**Comment by wparad** [comment]
Is the bot incorrectly flagging text as linkable even when it shouldn't be? I would expect it to be pretty good. But it's possible that your team is using Ids in a way which our logic isn't catching. Or are these correctly being identified as issue/tickets/items in your system that should probably have a link?

I'm trying to understand if there is a bug here, in which case we absolutely would want to fix it. Might you have an example you could share here, in the case that the bot is incorrectly identifying issue numbers?

Regarding the paid version, I'm sorry to hear that. I would appreciate understanding what the challenge there would be, if there is something missing for them that prevents enabling the features you would want, our team here would definitely want to know. So anything additional information you could provide would be helpful.

Thanks,
Warren

**Comment by castalos** [comment]
Our JIRA tickets look like this:   TBS-#####   The bot identifies that as a JIRA ticket and makes it a link as shown here: 
![image](https://user-images.githubusercontent.com/121258103/209242876-5eb1bb2a-bb32-4e1e-a353-aec5935afbb8.png)
instead of our JIRA instance which looks like this: https://....com/jira/browse/TBS-16244 .   

It seems that the tool default is set to make things in the format of KEY-xxx as links even if that option is not turned on - even though we're using the free version.   I would think the default would be to not match anything and not provide any links.

As for paid version, I work for a company with over 100K employees and trying to get something like this with recurring support charges (even though only a small number of people would actually use) is unfortunately a paperwork nightmare.

**Comment by wparad** [comment]
It's a good thought, we'll put it in our backlog. As for the product, the reason why it is there, is for discoverability. We want teams to be able to easily see that they have additional capabilities available to them if they choose to use them.

Regarding the issues with navigating your company. I can understand the challenges there. If there is anything we can do to ease that difficulty, please do let us know.
